version: 2

sphinx:
  builder: html

build:
  os: "ubuntu-22.04"
  tools:
    python: "3"
    rust: "1.61"

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs